In [4]:
import tensorflow as tf
from tensorflow.python.client import device_lib

In [8]:
print(tf.__version__)
#tf.config.list_physical_devices("GPU")
#print(device_lib.list_local_devices())

2.14.0


In [7]:
# Create tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
# Check dimensions
scalar.ndim

0

In [11]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
vector.ndim

1

In [13]:
# Create matrix
matrix = tf.constant([[10,8],[8,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 8, 10]], dtype=int32)>

In [14]:
matrix.ndim

2

In [15]:
matrix_2 = tf.constant([[1.,2.],[3.,4.],[5,6]], dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [17]:
matrix_3 = tf.constant([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]], [[13,14,15], [16,17,18]]])
matrix_3

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

# 9